FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY apps/inventory ./apps/inventory
COPY libs ./libs

RUN npm ci
RUN npm run build inventory

FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production && npm cache clean --force
COPY --from=builder /app/dist ./dist

CMD ["node", "dist/apps/inventory/main.js"]
