FROM node:20-bullseye AS builder
WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY apps/rewards ./apps/rewards
COPY libs ./libs

RUN npm ci
RUN npx prisma generate --schema=apps/rewards/prisma/schema.prisma
RUN npm run build rewards

FROM node:20-bullseye
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production && npm cache clean --force
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma
COPY --from=builder /app/node_modules/prisma ./node_modules/prisma
COPY --from=builder /app/dist ./dist

CMD ["node", "dist/apps/rewards/main.js"]
