FROM node:20-bullseye AS builder
WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY apps/payments ./apps/payments
COPY libs ./libs

RUN npm ci
RUN npx prisma generate --schema=apps/payments/prisma/schema.prisma
RUN npm run build payments

FROM node:20-bullseye
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production && npm cache clean --force
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma

CMD ["node", "dist/apps/payments/main.js"]
